
name: Build, test and deploy React Application


on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build_test:
    permissions:               
        contents: write        
        pull-requests: write   
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [25.2.1]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: npm ci and test
        run: |
          npm ci
          npm test  
        env: 
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build and docs
        run: |
          npm run jsdoc
          npm run build --if-present
        env: 
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
      - name: build and publish package on NPM 📦
        run: |
          git config --global user.email "loise.fenoll@ynov.com"
          git config --global user.name "Loise Fenoll"
          npm run build-npm
          npm version patch --no-git-tag-version
          npm publish
          git add .
          git commit -m "updated version"
          git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
